import { Link } from 'react-router-dom'
import { HeroArt } from '../components/SiteShell'
import { leagueData, leaguePath } from '../data'
import { readPreferences } from '../lib/preferences'
import { leagueNames } from '../types'

export function HomePage() {
  const preferences = readPreferences()
  const orderedLeagues = preferences ? [...leagueNames].sort((first, second) => Number(preferences.leagues.includes(second)) - Number(preferences.leagues.includes(first))) : [...leagueNames]
  return <><section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span className="live-dot" /> The pulse of the game</p><h1>Everything<br /><em>Volleyball.</em><br />One Place.</h1><p className="hero-description">Scores, stories, schedules, and the moments that make the sport impossible to ignore.</p><Link className="primary-button" to={preferences ? leaguePath(preferences.leagues[0]) : '/preferences'}>{preferences ? 'Explore your coverage' : 'Set your preferences'} <span aria-hidden="true">↓</span></Link></div><HeroArt /><div className="scroll-note"><span>Scroll to explore</span><i /></div></section><section className="personalized-bar" aria-live="polite">{preferences ? <><span className="eyebrow">Your homepage</span><strong>Prioritized for {preferences.profile}</strong><span>{preferences.leagues.join(' · ')}</span><Link to="/preferences">Update preferences</Link></> : <><span className="eyebrow">Make it yours</span><strong>Create your account to personalize homepage coverage.</strong><Link to="/preferences">Get started <span aria-hidden="true">↗</span></Link></>}</section><section className="league-section" id="leagues"><div className="section-heading"><div><p className="eyebrow">Your game, your way</p><h2>Choose your<br /><em>court.</em></h2></div><p>{preferences ? `Coverage prioritized for ${preferences.profile.toLowerCase()} interests.` : 'From college rivalries to the newest pro leagues, stay close to every side of volleyball.'}</p></div><div className="league-grid">{orderedLeagues.map((name, index) => { const league = leagueData[name]; return <Link className={`league-card ${league.tone} ${preferences?.leagues.includes(name) ? 'is-preferred' : ''}`} to={leaguePath(name)} key={name}><span className="card-number">0{index + 1}</span><span className="card-arrow" aria-hidden="true">↗</span><span className="card-content"><strong>{name}</strong><small>{league.detail}</small></span></Link> })}</div></section><section className="coverage-section"><div className="section-heading"><div><p className="eyebrow">MVP coverage</p><h2>Follow the<br /><em>current.</em></h2></div><p>Scores, schedules, standings, and attributed news links across every supported league.</p></div><div className="coverage-grid">{orderedLeagues.map((name) => <Link className="coverage-item" to={leaguePath(name)} key={name}><span>{name}</span><h3>Scores, schedules, standings</h3><p>Realistic placeholder coverage for the current MVP build.</p><span className="coverage-link">View coverage ↗</span></Link>)}</div></section><section className="latest-section"><p className="eyebrow">Inside the lines</p><div className="latest-row"><h2>The latest <em>rally.</em></h2><Link to="/leagues/ncaa-d1" className="text-link">View all coverage <span aria-hidden="true">↗</span></Link></div></section></>
}
